# Lexical chunks: (korean, russian, english)
# Extensions: 10 phrases per legacy topic (orders 6-15)
# New topics 15-22: 15 phrases each (orders 1-15)

EXTENSIONS_BY_TOPIC_ID = {
    1: [
        ("이거 있어요?", "Это есть в наличии?", "Do you have this?"),
        ("다른 색 있어요?", "Есть другой цвет?", "Do you have another color?"),
        ("할인해요?", "Есть скидка?", "Is there a discount?"),
        ("봉투 필요 없어요.", "Пакет не нужен.", "I don't need a bag."),
        ("현금으로 낼게요.", "Заплачу наличными.", "I'll pay in cash."),
        ("영수증 필요 없어요.", "Чек не нужен.", "I don't need a receipt."),
        ("교환할 수 있어요?", "Можно обменять?", "Can I exchange this?"),
        ("환불해 주세요.", "Верните деньги, пожалуйста.", "Please give me a refund."),
        ("세일 중인가요?", "Это по акции?", "Is this on sale?"),
        ("좀 더 싼 거 있어요?", "Есть подешевле?", "Do you have something cheaper?"),
    ],
    2: [
        ("여기서 먹을게요.", "Буду есть здесь.", "For here, please."),
        ("얼음 빼 주세요.", "Без льда, пожалуйста.", "No ice, please."),
        ("디카페인으로 주세요.", "Декаф, пожалуйста.", "Decaf, please."),
        ("오트밀크로 바꿔 주세요.", "Замените на овсяное молоко.", "Oat milk, please."),
        ("와이파이 비밀번호 뭐예요?", "Какой пароль от Wi‑Fi?", "What's the Wi‑Fi password?"),
        ("콘센트 자리 있어요?", "Есть место у розетки?", "Is there a seat near an outlet?"),
        ("물 한 잔 더 주세요.", "Ещё воды, пожалуйста.", "Another water, please."),
        ("맵지 않게 해 주세요.", "Не острое, пожалуйста.", "Not spicy, please."),
        ("추천 메뉴 뭐예요?", "Что посоветуете?", "What do you recommend?"),
        ("맛있게 드세요.", "Приятного аппетита. (в ответ)", "Enjoy your meal."),
    ],
    3: [
        ("교통카드 충전하고 싶어요.", "Хочу пополнить транспортную карту.", "I'd like to recharge my transit card."),
        ("어린이 요금이에요?", "Это детский тариф?", "Is this the child fare?"),
        ("막차가 몇 시예요?", "Во сколько последний поезд?", "What time is the last train?"),
        ("이쪽이 맞아요?", "Это правильная сторона?", "Is this the right direction?"),
        ("좌석에 앉아도 돼요?", "Можно сидеть?", "May I sit down?"),
        ("내릴 때 카드 찍어요?", "При выходе тоже приложить карту?", "Do I tap when getting off?"),
        ("엘리베이터가 어디예요?", "Где лифт?", "Where is the elevator?"),
        ("장애인 출입구가 어디예요?", "Где вход для маломобильных?", "Where is the accessible entrance?"),
        ("분실물 센터가 어디예요?", "Где бюро находок?", "Where is the lost and found?"),
        ("길을 잃었어요.", "Я заблудился.", "I'm lost."),
    ],
    4: [
        ("종점까지 가요?", "До конечной?", "Does it go to the terminal?"),
        ("하차 벨 눌러 주세요.", "Нажмите кнопку выхода, пожалуйста.", "Please press the stop button."),
        ("자리 비었어요?", "Место свободно?", "Is this seat taken?"),
        ("앞문으로 타도 돼요?", "Можно войти через переднюю дверь?", "Can I board at the front?"),
        ("교통카드 잔액이 부족해요.", "На карте не хватает денег.", "My card balance is low."),
        ("환승 할인 되나요?", "Есть скидка на пересадку?", "Is there a transfer discount?"),
        ("버스가 언제 와요?", "Когда приедет автобус?", "When will the bus come?"),
        ("급정거하지 마세요.", "Не резко тормозите, пожалуйста.", "Please don't brake suddenly."),
        ("창문 열어도 돼요?", "Можно открыть окно?", "Can I open the window?"),
        ("정류장 이름이 뭐예요?", "Как называется эта остановка?", "What's this stop called?"),
    ],
    5: [
        ("미터기 켜 주세요.", "Включите счётчик, пожалуйста.", "Please turn on the meter."),
        ("택시 불러 주세요.", "Вызовите такси, пожалуйста.", "Please call a taxi."),
        ("짐 넣어 주세요.", "Положите багаж, пожалуйста.", "Please put my luggage in."),
        ("트렁크 열어 주세요.", "Откройте багажник, пожалуйста.", "Please open the trunk."),
        ("여기 주소로 가 주세요.", "По этому адресу, пожалуйста.", "To this address, please."),
        ("빨리 가 주세요.", "Пожалуйста, быстрее.", "Please hurry."),
        ("천천히 가 주세요.", "Пожалуйста, помедленнее.", "Please drive slowly."),
        ("카카오택시 불렀어요.", "Я вызвал через Kakao Taxi.", "I called via Kakao Taxi."),
        ("팁은 없어도 돼요?", "Чаевые не нужны?", "No tip needed?"),
        ("영수증 필요 없어요.", "Чек не нужен.", "No receipt needed."),
    ],
    6: [
        ("출입국 심사는 어디예요?", "Где паспортный контроль?", "Where is immigration?"),
        ("세관 신고해야 해요?", "Нужно декларировать?", "Do I need to declare?"),
        ("면세점이 어디예요?", "Где duty free?", "Where is duty free?"),
        ("환전소가 어디예요?", "Где обмен валюты?", "Where is currency exchange?"),
        ("기내 반입 가능해요?", "Можно взять в салон?", "Can I take this on board?"),
        ("액체류 반입 돼요?", "Можно провозить жидкости?", "Can I bring liquids?"),
        ("좌석 변경하고 싶어요.", "Хочу сменить место.", "I'd like to change my seat."),
        ("수하물 찾는 곳이 어디예요?", "Где выдача багажа?", "Where is baggage claim?"),
        ("환승 안내해 주세요.", "Подскажите по пересадке.", "Please help with my connection."),
        ("공항 셔틀버스 어디서 타요?", "Откуда шаттл по аэропорту?", "Where is the airport shuttle?"),
    ],
    7: [
        ("KTX표 주세요.", "Билет на KTX, пожалуйста.", "A KTX ticket, please."),
        ("좌석 번호가 어디예요?", "Где моё место?", "Where is my seat?"),
        ("중간에 내려요.", "Выходу по пути.", "I'm getting off midway."),
        ("표 검사해 주세요.", "Проверьте билет, пожалуйста.", "Please check my ticket."),
        ("짐 위에 올려도 돼요?", "Можно положить сумку наверх?", "Can I put my bag overhead?"),
        ("정차역 알려 주세요.", "Скажите, когда моя станция.", "Please tell me when we arrive."),
        ("늦지 않게 도착할게요.", "Приеду вовремя.", "I'll arrive on time."),
        ("역 앞에서 만나요.", "Встретимся у выхода станции.", "Meet me in front of the station."),
        ("표 환불하고 싶어요.", "Хочу вернуть билет.", "I'd like a refund on my ticket."),
        ("할인 받을 수 있어요?", "Можно получить скидку?", "Can I get a discount?"),
    ],
    8: [
        ("고속버스 터미널이 어디예요?", "Где автовокzal экспресс-бусов?", "Where is the express bus terminal?"),
        ("좌석 지정석이에요?", "Места фиксированные?", "Are seats assigned?"),
        ("창가 자리로 바꿔 주세요.", "Поменяйте на место у окна.", "Window seat, please."),
        ("중간 휴게소에서 쉬어요?", "Будет остановка на rest area?", "Is there a rest stop?"),
        ("버스가 지연됐어요?", "Автобус задерживается?", "Is the bus delayed?"),
        ("표를 분실했어요.", "Я потерял билет.", "I lost my ticket."),
        ("다음 버스는 몇 시예요?", "Следующий автобус во сколько?", "What time is the next bus?"),
        ("싣긴 짐 무게 제한이 있어요?", "Есть лимит на багаж?", "Is there a luggage weight limit?"),
        ("안전벨트 매 주세요.", "Пристегните ремень, пожалуйста.", "Please fasten your seatbelt."),
        ("목적지까지 얼마나 걸려요?", "Сколько ехать до пункта назначения?", "How long until we arrive?"),
    ],
    9: [
        ("구명조끼 꼭 입어야 해요?", "Обязательно надевать спасжилет?", "Must I wear a life vest?"),
        ("파라솔 빌릴 수 있어요?", "Можно арендовать зонт?", "Can I rent a parasol?"),
        ("수영해도 돼요?", "Можно купаться?", "Is swimming allowed?"),
        ("조심하세요, 파도가 커요.", "Осторожно, большие волны.", "Careful, the waves are big."),
        ("구조대 번호가 뭐예요?", "Какой номер спасателей?", "What's the lifeguard number?"),
        ("쓰레기통이 어디예요?", "Где урна?", "Where is the trash bin?"),
        ("선크림 있어요?", "Есть солнцезащитный крем?", "Do you have sunscreen?"),
        ("물놀이 금지 구역이에요?", "Здесь купание запрещено?", "Is swimming prohibited here?"),
        ("샌들 팔아요?", "Продаёте шлёпанцы?", "Do you sell sandals?"),
        ("일몰 시간이 몇 시예요?", "Во сколько закат?", "What time is sunset?"),
    ],
    10: [
        ("자전거 대여할 수 있어요?", "Можно взять велосипед?", "Can I rent a bicycle?"),
        ("반려동물 데려와도 돼요?", "Можно с питомцем?", "Are pets allowed?"),
        ("쓰레기 가져가 주세요.", "Заберите мусор, пожалуйста.", "Please take your trash."),
        ("조용히 해 주세요.", "Пожалуйста, тише.", "Please be quiet."),
        ("길이 어디로 이어져요?", "Куда ведёт эта дорожка?", "Where does this path go?"),
        ("분수대가 어디예요?", "Где фонтан?", "Where is the fountain?"),
        ("운동기구 사용해도 돼요?", "Можно пользоваться тренажёрами?", "Can I use the exercise equipment?"),
        ("공원이 몇 시에 닫아요?", "Во сколько парк закрывается?", "What time does the park close?"),
        ("지도 있어요?", "Есть карта парка?", "Do you have a map?"),
        ("물 마실 곳이 어디예요?", "Где питьевая вода?", "Where can I get drinking water?"),
    ],
    11: [
        ("수영복 입고 와야 해요?", "Нужно прийти уже в купальнике?", "Should I come in a swimsuit?"),
        ("락커 열쇠를 잃어버렸어요.", "Я потерял ключ от камеры хранения.", "I lost my locker key."),
        ("안전요원이 어디 있어요?", "Где спасатель?", "Where is the lifeguard?"),
        ("미끄럼 주의해 주세요.", "Осторожно, скользко.", "Caution, slippery."),
        ("아이랑 같이 타도 돼요?", "Можно кататься с ребёнком?", "Can I ride with a child?"),
        ("대기 시간이 얼마나 걸려요?", "Сколько ждать?", "How long is the wait?"),
        ("온수풀은 어디예요?", "Где бассейн с тёплой водой?", "Where is the heated pool?"),
        ("신발 벗고 들어가요?", "Обувь снимать?", "Do I take off my shoes?"),
        ("구급함이 어디예요?", "Где аптечка?", "Where is the first aid kit?"),
        ("재입장 가능해요?", "Можно выйти и зайти снова?", "Can I re-enter?"),
    ],
    12: [
        ("외국인등록증 발급받으러 왔어요.", "Пришёл оформить ARC.", "I came to apply for an ARC."),
        ("체류 기간 연장 신청할게요.", "Подам на продление срока пребывания.", "I'll apply to extend my stay."),
        ("지문 찍어야 해요?", "Нужно сдавать отпечатки?", "Do I need fingerprinting?"),
        ("사진 규격이 어떻게 돼요?", "Какие требования к фото?", "What are the photo requirements?"),
        ("수수료는 얼마예요?", "Сколько госпошлина?", "What's the fee?"),
        ("온라인으로 예약했어요.", "Я записался онлайн.", "I booked online."),
        ("서류가 부족한가요?", "Не хватает документов?", "Are my documents incomplete?"),
        ("처리 기간이 얼마나 걸려요?", "Сколько ждать решения?", "How long does processing take?"),
        ("주소 변경 신고할게요.", "Сообщу о смене адреса.", "I'll report a change of address."),
        ("출입국 기록 확인해 주세요.", "Проверьте историю въездов/выездов.", "Please check my entry/exit record."),
    ],
    13: [
        ("실례합니다.", "Извините (привлечь внимание).", "Excuse me."),
        ("죄송합니다.", "Мне жаль / извините.", "I'm sorry."),
        ("괜찮아요.", "Всё в порядке.", "It's okay."),
        ("처음 뵙겠습니다.", "Рад познакомиться (формально).", "Nice to meet you (formal)."),
        ("이름이 뭐예요?", "Как вас зовут?", "What's your name?"),
        ("연락처 알려 드릴게요.", "Дам контакт.", "I'll give you my contact."),
        ("나중에 연락할게요.", "Свяжусь позже.", "I'll contact you later."),
        ("좋은 하루 보내세요.", "Хорошего дня.", "Have a good day."),
        ("다음에 또 봬요.", "До встречи.", "See you again."),
        ("천천히 말해 주세요.", "Говорите медленнее, пожалуйста.", "Please speak slowly."),
    ],
    14: [
        ("펌 해 주세요.", "Сделайте химическую завивку.", "Perm, please."),
        ("염색하지 말아 주세요.", "Не красьте, пожалуйста.", "No dye, please."),
        ("같은 스타일로 해 주세요.", "Как в прошлый раз.", "Same style as last time."),
        ("두피가 따가워요.", "Кожа головы щиплет.", "My scalp stings."),
        ("얼마나 걸려요?", "Сколько по времени?", "How long will it take?"),
        ("예약했어요.", "У меня запись.", "I have a reservation."),
        ("스타일 추천해 주세요.", "Посоветуйте стрижку.", "Recommend a style."),
        ("손질만 해 주세요.", "Только укладка.", "Styling only, please."),
        ("너무 뜨거워요.", "Слишком горячо.", "It's too hot."),
        ("만족해요, 감사합니다.", "Доволен, спасибо.", "I'm happy with it, thanks."),
    ],
}

NEW_TOPIC_PHRASES = {
    15: [
        ("경찰관님, 도와주세요.", "Офицер, помогите, пожалуйста.", "Officer, please help me."),
        ("지갑을 잃어버렸어요.", "Я потерял кошелёк.", "I lost my wallet."),
        ("휴대폰 도난당했어요.", "У меня украли телефон.", "My phone was stolen."),
        ("길을 잃었어요.", "Я заблудился.", "I'm lost."),
        ("사고가 났어요.", "Произошла авария.", "There was an accident."),
        ("신고하려고요.", "Хочу заявить.", "I'd like to report it."),
        ("목격자예요.", "Я свидетель.", "I'm a witness."),
        ("통역이 필요해요.", "Нужен переводчик.", "I need an interpreter."),
        ("여권 사본 있어요.", "У меня есть копия паспорта.", "I have a copy of my passport."),
        ("가까운 파출소가 어디예요?", "Где ближайший участок?", "Where is the nearest police box?"),
        ("112에 전화했어요.", "Я звонил на 112.", "I called 112."),
        ("진술서 써야 해요?", "Нужно писать показания?", "Do I need to write a statement?"),
        ("CCTV 확인해 주세요.", "Проверьте камеры, пожалуйста.", "Please check the CCTV."),
        ("조심하세요, 위험해요.", "Осторожно, опасно.", "Careful, it's dangerous."),
        ("감사합니다, 수고하세요.", "Спасибо, хорошей смены.", "Thank you, take care."),
    ],
    16: [
        ("신고 접수하러 왔어요.", "Пришёл подать заявление.", "I came to file a report."),
        ("분실 신고할게요.", "Заявлю о потере.", "I'll report a loss."),
        ("여권을 분실했어요.", "Я потерял паспорт.", "I lost my passport."),
        ("도장 찍어 주세요.", "Поставьте печать, пожалуйста.", "Please stamp this."),
        ("접수 번호 받았어요.", "Мне дали номер обращения.", "I received a case number."),
        ("처리 결과 언제 알 수 있어요?", "Когда будет результат?", "When will I know the outcome?"),
        ("서명하면 돼요?", "Достаточно подписи?", "Should I sign here?"),
        ("통역사 불러 주세요.", "Позовите переводчика.", "Please call an interpreter."),
        ("대기해야 해요?", "Нужно ждать?", "Do I need to wait?"),
        ("오늘 접수 가능해요?", "Сегодня можно подать?", "Can I file today?"),
        ("신분증 보여 드릴게요.", "Покажу удостоверение.", "I'll show my ID."),
        ("사진이 필요해요?", "Нужны фотографии?", "Do you need photos?"),
        ("연락처 남겨도 돼요?", "Можно оставить контакт?", "May I leave my contact?"),
        ("복사본 받을 수 있어요?", "Можно получить копию?", "Can I get a copy?"),
        ("수고하셨습니다.", "Спасибо за работу.", "Thank you for your service."),
    ],
    17: [
        ("원룸 구하러 왔어요.", "Ищу студию.", "I'm looking for a studio."),
        ("월세 얼마예요?", "Сколько 월 аренды?", "What's the monthly rent?"),
        ("보증금은 얼마예요?", "Сколько залог?", "What's the deposit?"),
        ("관리비 포함이에요?", "Коммуналка включена?", "Are utilities included?"),
        ("계약 기간이 어떻게 돼요?", "На какой срок договор?", "What's the lease term?"),
        ("집 보여 주세요.", "Покажите квартиру.", "Please show me the place."),
        ("역에서 가까워요?", "Близко к станции?", "Is it close to the subway?"),
        ("반려동물 가능해요?", "Можно с животными?", "Are pets allowed?"),
        ("전입 신고 도와주세요.", "Помогите с регистрацией по месту жительства.", "Help with address registration."),
        ("에어컨 있어요?", "Есть кондиционер?", "Is there air conditioning?"),
        ("사진이랑 같아요?", "Как на фото?", "Is it like the photos?"),
        ("계약서 검토할게요.", "Проверю договор.", "I'll review the contract."),
        ("중개 수수료 얼마예요?", "Сколько комиссия агентства?", "What's the agency fee?"),
        ("입주 가능일이 언제예요?", "Когда можно заселиться?", "When can I move in?"),
        ("다른 매물 더 있어요?", "Есть другие варианты?", "Do you have other listings?"),
    ],
    18: [
        ("집주인님, 안녕하세요.", "Здравствуйте, хозяин.", "Hello, landlord."),
        ("수도가 안 나와요.", "Не идёт вода.", "The water isn't working."),
        ("보일러가 고장 났어요.", "Сломался котёл.", "The boiler is broken."),
        ("에어컨이 작동 안 해요.", "Кондиционер не работает.", "The AC doesn't work."),
        ("수리해 주실 수 있어요?", "Можете отремонтировать?", "Can you fix it?"),
        ("월세 송금했어요.", "Перевёл аренду.", "I sent the rent."),
        ("계약 연장하고 싶어요.", "Хочу продлить договор.", "I'd like to renew the lease."),
        ("퇴실일 알려 드릴게요.", "Сообщу дату выезда.", "I'll tell you my move-out date."),
        ("청소하고 퇴실할게요.", "Уберусь перед выездом.", "I'll clean before moving out."),
        ("보증금 돌려받을 수 있어요?", "Вернёте залог?", "Can I get my deposit back?"),
        ("쓰레기 버리는 곳이 어디예요?", "Куда выносить мусор?", "Where do I throw trash?"),
        ("배달 올 때 연락드릴게요.", "Позвоню, когда приедет доставка.", "I'll call when delivery arrives."),
        ("시끄럽지 않게 할게요.", "Постараюсь не шуметь.", "I'll keep quiet."),
        ("방문 코드 알려 주세요.", "Дайте код от двери.", "Please give me the door code."),
        ("감사합니다, 잘 지낼게요.", "Спасибо, буду аккуратно жить.", "Thanks, I'll take good care of the place."),
    ],
    19: [
        ("주민등록 등록하러 왔어요.", "Пришёл зарегистрироваться по месту жительства.", "I came to register my address."),
        ("외국인 등록증 재발급받으러 왔어요.", "На перевыпуск ARC.", "I came to reissue my ARC."),
        ("서류 접수 창구가 어디예요?", "Где окно приёма документов?", "Where is the document counter?"),
        ("번호표 뽑아야 해요?", "Нужно взять талон?", "Do I need a ticket number?"),
        ("대기 시간이 얼마나 돼요?", "Сколько ждать?", "How long is the wait?"),
        ("신청서 작성 도와주세요.", "Помогите заполнить заявление.", "Please help me fill out the form."),
        ("인감 도장 필요해요?", "Нужна печать?", "Do I need a seal stamp?"),
        ("수수료 어디서 내나요?", "Где платить пошлину?", "Where do I pay the fee?"),
        ("온라인 예약했어요.", "Записался онлайн.", "I booked online."),
        ("통역 서비스 있나요?", "Есть перевод?", "Is interpretation available?"),
        ("증명서 발급받고 싶어요.", "Нужна справка.", "I'd like a certificate issued."),
        ("주소 변경 신고할게요.", "Сообщу о смене адреса.", "I'll report a change of address."),
        ("필요한 서류 목록 알려 주세요.", "Список нужных документов, пожалуйста.", "Please tell me required documents."),
        ("처리 완료되면 연락 주세요.", "Свяжитесь, когда будет готово.", "Contact me when it's done."),
        ("감사합니다.", "Спасибо.", "Thank you."),
    ],
    20: [
        ("종합소득세 신고하러 왔어요.", "Пришёл подать декларацию о доходах.", "I came to file income tax."),
        ("외국인도 신고해야 해요?", "Иностранцам тоже нужно?", "Do foreigners need to file too?"),
        ("신고 기간이 언제까지예요?", "До какого числа подача?", "What's the filing deadline?"),
        ("온라인으로 신고할게요.", "Подам онлайн.", "I'll file online."),
        ("세금 계산 도와주세요.", "Помогите рассчитать налог.", "Please help calculate my tax."),
        ("환급 받을 수 있어요?", "Можно получить возврат?", "Can I get a refund?"),
        ("납부서 발급해 주세요.", "Выдайте квитанцию на оплату.", "Please issue a payment slip."),
        ("사업자등록증 보여 드릴게요.", "Покажу регистрацию бизнеса.", "I'll show my business registration."),
        ("공제 항목이 뭐예요?", "Какие вычеты есть?", "What deductions are there?"),
        ("체납은 없어요.", "Задолженности нет.", "I have no overdue tax."),
        ("상담 예약했어요.", "У меня запись на консультацию.", "I have a consultation appointment."),
        ("통역 필요합니다.", "Нужен переводчик.", "I need an interpreter."),
        ("서류 제출했어요.", "Документы уже подал.", "I already submitted documents."),
        ("처리 결과 우편으로 보내 주세요.", "Пришлите результат почтой.", "Send the result by mail."),
        ("수고하십니다.", "Спасибо за работу.", "Thank you for your work."),
    ],
    21: [
        ("유심 칩 사러 왔어요.", "Пришёл купить SIM.", "I came to buy a SIM."),
        ("선불 요금제 있어요?", "Есть предоплата?", "Do you have prepaid plans?"),
        ("여권 보여 드릴게요.", "Покажу паспорт.", "I'll show my passport."),
        ("외국인 등록증 있어요.", "У меня есть ARC.", "I have an ARC."),
        ("데이터 무제한 요금제예요?", "Безлимитный интернет?", "Is this unlimited data?"),
        ("번호 이식하고 싶어요.", "Хочу перенести номер.", "I'd like to port my number."),
        ("개통해 주세요.", "Активируйте, пожалуйста.", "Please activate it."),
        ("APN 설정 도와주세요.", "Помогите настроить APN.", "Please help set up APN."),
        ("eSIM 가능해요?", "Можно eSIM?", "Is eSIM available?"),
        ("월 요금이 얼마예요?", "Сколько в месяц?", "What's the monthly fee?"),
        ("약정 기간이 있어요?", "Есть контракт на срок?", "Is there a contract period?"),
        ("해지하면 위약금 있어요?", "Штраф при расторжении?", "Is there a cancellation fee?"),
        ("충전 어떻게 해요?", "Как пополнять?", "How do I top up?"),
        ("와이파이 라우터도 팔아요?", "Продаёте Wi‑Fi роутеры?", "Do you sell Wi‑Fi routers?"),
        ("감사합니다.", "Спасибо.", "Thank you."),
    ],
    22: [
        ("계좌 개설하러 왔어요.", "Открыть счёт.", "I came to open an account."),
        ("여권과 외국인등록증 있어요.", "Есть паспорт и ARC.", "I have my passport and ARC."),
        ("인터넷 뱅킹 신청할게요.", "Подключу интернет-банк.", "I'd like internet banking."),
        ("체크카드 발급받고 싶어요.", "Нужна дебетовая карта.", "I'd like a debit card."),
        ("송금하려고요.", "Хочу перевести деньги.", "I'd like to send money."),
        ("해외 송금 가능해요?", "Можно за границу?", "Can I remit abroad?"),
        ("수수료가 얼마예요?", "Какая комission?", "What's the fee?"),
        ("통장 사본 발급해 주세요.", "Выписку/копию счёта, пожалуйста.", "Please issue a bank book copy."),
        ("비밀번호 변경하고 싶어요.", "Сменить PIN.", "I'd like to change my PIN."),
        ("카드 분실 신고할게요.", "Заявлю о потере карты.", "I'll report a lost card."),
        ("OTP 발급받았어요.", "Получил OTP.", "I got an OTP token."),
        ("대출 상담 받을 수 있어요?", "Консультация по кредиту?", "Can I get a loan consultation?"),
        ("영업 시간이 어떻게 돼요?", "Часы работы?", "What are your hours?"),
        ("ATM은 어디 있어요?", "Где банкомат?", "Where is the ATM?"),
        ("감사합니다.", "Спасибо.", "Thank you."),
    ],
}
